[package]
name = "san_vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sanscript_common = {path= "../sanscript-common" }
sanscript_frontend = {path= "../sanscript-frontend" }